name: metpy-ams-2023
channels:
  - conda-forge
dependencies:
  - python==3.11.0
  - cartopy==0.21.1
  - jupyterlab==3.5.2
  - matplotlib==3.6.2
  - metpy==1.4.0
  - numpy==1.24.1
  - pykdtree==1.3.6
  - siphon==0.9
  - arm_pyart==1.14.1
  - fsspec==2022.11.0
  - s3fs==2022.11.0
  